FROM node:20-alpine AS base

RUN npm install -g pnpm
RUN apk add --no-cache libc6-compat

ENV APP_ENV=local

WORKDIR /app

# Copy dependency files first for caching
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

# Copy the rest of the project
COPY . .

FROM base AS local

EXPOSE 3000
CMD ["pnpm", "run", "dev"]
